[unix_http_server]
file=/home/prolog/.config/alteru-prolog/supervisor.sock
chmod=0600

[supervisord]
logfile=/home/prolog/alteru-prolog-experiment/log/supervisord.log
pidfile=/home/prolog/.config/alteru-prolog/supervisord.pid
childlogdir=/home/prolog/alteru-prolog-experiment/log
nodaemon=false
minfds=1024

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///home/prolog/.config/alteru-prolog/supervisor.sock

[program:mist-harbor-rule-service]
command=/home/prolog/alteru-prolog-experiment/start_production_service.sh
directory=/home/prolog/alteru-prolog-experiment
autostart=true
autorestart=true
startsecs=3
startretries=5
stopsignal=TERM
stopwaitsecs=10
redirect_stderr=true
stdout_logfile=/home/prolog/alteru-prolog-experiment/log/mist-harbor-supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
